{
    "name": "Sonos",
    "version": "1.0.1",
    "icon": "fas fa-music",
    "category": "music",
    "author": "Psychokiller1888",
    "maintainers": [],
    "desc": "Let alice control your sonos hardware",
    "aliceMinVersion": "1.0.0-a6",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
        "soco"
    ],
    "conditions": {
        "lang": [
            "en"
        ],
        "asrArbitraryCapture": true
    }
}
