{
    "name": "Sonos",
    "version": "1.0.10",
    "icon": "fas fa-music",
    "category": "music",
    "author": "Psychokiller1888",
    "maintainers": [
        "Fe3lApAcUt"
    ],
    "desc": "Let alice control your sonos hardware",
    "aliceMinVersion": "1.0.0-b3",
    "systemRequirements": [
        ""
    ],
    "pipRequirements": [
        "soco"
    ],
    "conditions": {
        "lang": [
            "en",
            "de"
        ],
        "asrArbitraryCapture": true
    }
}